server:
  port: 8000
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
#logging:
#    level:
#      com.elfLab.bbgg.mapper.BoardMapper: debug
#      com.elfLab.bbgg.mapper.UserMapper: debug
#      com.elfLab.bbgg.mapper.CommentMapper: debug 
#      com.elfLab.bbgg.mapper.AttachMapper: debug

  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/threeam?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: tam
    password: 1234

  jackson:
    serialization:
      fail-on-empty-beans: false
